'use client';
import { useEffect, useRef, useState } from 'react';
import { PHASE_RULES, PAIRING_POLICY, type PhaseSummary, type Region, type Comparison, type Relationship, type Segment } from '../../lib/obd/drive';
import type { LogInfo, Trace } from '../../lib/obd/types';
import type { LogWorkerClient } from '../../lib/obd/worker-client';
import type { Run } from '../../lib/obd/drive-session';
import type { ImportPreview as Preview } from '../../lib/obd/mapping';
import type { MappingConfig } from '../../lib/obd/mapping-types';
import ImportPreview from './import-preview';

const n = (v: number | null | undefined) => v == null ? '—' : v.toLocaleString('en', { maximumFractionDigits: 3 });
const label = (s: Segment) => `${s.phase} · ${n(s.start)}–${n(s.end)} s (${n(s.duration)} s)`;
const pct = (v: number) => `${Math.round(v * 100)}%`;
function TracePlot({ data, segment, run, unit, limits }: { data: Trace; segment: Segment; run: Run; unit: string; limits: [number, number] }) {
  const [min, max] = limits, span = max - min || 1;
  const path = data.points.map((p, i, all) => p.value === null ? '' : `${i && all[i - 1].value !== null ? 'L' : 'M'}${10 + (p.time - segment.start) / (segment.duration || 1) * 380},${130 - (p.value - min) / span * 115}`).join(' ');
  return <figure className={`drive-plot run-${run}`}><figcaption>Run {run} · {unit} · {n(data.count)} samples</figcaption><div className="drive-axis">Y: {n(min)} to {n(max)} {unit}</div><svg role="img" aria-label={`Run ${run} relative-time trace`} viewBox="0 0 400 150"><path d="M10,10V135H390" stroke="#546270" fill="none" /><path d={path} stroke={run === 'A' ? '#5baaff' : '#f3bc5b'} strokeWidth="2" fill="none" /></svg><div className="drive-axis"><span>0 s</span><span>{n(segment.duration)} s from region start</span></div></figure>;
}
function Scatter({ data, xLabel, yLabel }: { data: Relationship; xLabel: string; yLabel: string }) {
  const xr = data.xRange ?? [0, 1], yr = data.yRange ?? [0, 1];
  return <figure className="drive-plot"><figcaption>{yLabel} versus {xLabel}</figcaption><p className="drive-axis">Y: {n(yr[0])}–{n(yr[1])}</p><svg role="img" aria-label="PID relationship scatter" viewBox="0 0 400 240"><path d="M12,10V222H390" stroke="#546270" fill="none" />{data.points.map((p, i) => <circle key={i} cx={12 + (p.x - xr[0]) / (xr[1] - xr[0] || 1) * 376} cy={220 - (p.y - yr[0]) / (yr[1] - yr[0] || 1) * 206} r="2.5" fill="#52d6b1" opacity="0.65" />)}</svg><p className="drive-axis">X: {n(xr[0])}–{n(xr[1])} · {data.points.length} displayed pairs</p></figure>;
}
function RegionStats({ data, run }: { data: Region; run: Run }) {
  return <div className="drive-region" data-testid={`region-${run}`}><h4>Run {run}: {label(data.segment)}</h4><p>{data.segment.evidence}</p><p className="obd-footnote">{data.segment.caveat}</p><details><summary>Full-resolution phase statistics</summary><p>Closed interval endpoints. Mean and median are sample-weighted. Coverage is the fraction of region duration spanned by consecutive numeric samples ≤2 s apart; it does not imply continuous measurement.</p><div className="drive-stat-grid">{data.stats.map(s => <article key={s.id}><strong>{s.identity ?? s.id} · {s.unit ?? 'unknown unit'}</strong><span>Median {n(s.median)} · mean {n(s.mean)}</span><span>Min {n(s.min)} · max {n(s.max)}</span><small>{n(s.count)} samples · coverage {pct(s.coverage)} · median cadence {n(s.cadence)} s</small></article>)}</div></details></div>;
}
export default function DriveAnalysis({ client, info, name, onInspect, onCancel }: { client: LogWorkerClient; info: LogInfo; name: string; onInspect: (time: number) => void; onCancel: () => void }) {
  const [summaries, setSummaries] = useState<Partial<Record<Run, PhaseSummary>>>({});
  const [ids, setIds] = useState<Record<Run, number>>({ A: -1, B: -1 });
  const [regions, setRegions] = useState<Partial<Record<Run, Region>>>({});
  const [bInfo, setBInfo] = useState<LogInfo | null>(null), [bName, setBName] = useState('');
  const [preview, setPreview] = useState<Preview | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [comparison, setComparison] = useState<Comparison | null>(null), [identity, setIdentity] = useState(''), [plots, setPlots] = useState<{ a: Trace; b: Trace } | null>(null);
  const [context, setContext] = useState('Run 1 vs Run 2'), [relRun, setRelRun] = useState<Run>('A'), [x, setX] = useState(''), [y, setY] = useState(''), [tolerance, setTolerance] = useState(0.5), [rel, setRel] = useState<Relationship | null>(null);
  const mounted = useRef(true), generation = useRef(0);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const clearResults = () => { generation.current++; setComparison(null); setPlots(null); setRel(null); };
  const phasePage = async (run: Run, offset = 0) => {
    clearResults();
    const r = await client.request({ kind: 'phases', run, offset });
    if (!mounted.current || !('kind' in r) || r.kind !== 'phases') return;
    setSummaries(old => ({ ...old, [run]: r.summary })); setIds(old => ({ ...old, [run]: r.summary.segments[0]?.id ?? -1 }));
  };
  useEffect(() => {
    let active = true;
    client.request({ kind: 'phases', run: 'A' }).then(r => { if (active && 'kind' in r && r.kind === 'phases') { setSummaries(old => ({ ...old, A: r.summary })); setIds(old => ({ ...old, A: r.summary.segments[0]?.id ?? -1 })); setRegions({}); setComparison(null); setPlots(null); setRel(null); generation.current++; } }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [client, info]);
  useEffect(() => {
    let active = true;
    for (const run of ['A', 'B'] as const) if (ids[run] >= 0) client.request({ kind: 'region', run, segment: ids[run] }).then(r => { if (active && 'kind' in r && r.kind === 'region') setRegions(old => ({ ...old, [run]: r.region })); }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; };
  }, [client, ids, info, bInfo]);
  const act = async (task: () => Promise<void>) => {
    setBusy(true); setError('');
    try { await task(); } catch (e) { if (mounted.current) setError(e instanceof Error ? e.message : 'Analysis failed.'); }
    finally { if (mounted.current) setBusy(false); }
  };
  const loadB = (file: Blob, filename: string) => act(async () => {
    clearResults(); setBInfo(null); setBName(filename); setPreview(null); setRegions(old => ({ A: old.A })); setSummaries(old => ({ A: old.A })); setIds(old => ({ ...old, B: -1 }));
    const r = await client.request({ kind: 'load', run: 'B', file }); if (mounted.current && 'kind' in r && r.kind === 'preview') setPreview(r.preview);
  });
  const remapB = async (config?: MappingConfig) => {
    let value: Preview | null = null;
    await act(async () => { const r = await client.request(config ? { kind: 'remap', run: 'B', config } : { kind: 'review', run: 'B' }); if (mounted.current && 'kind' in r && r.kind === 'preview') { value = r.preview; setPreview(value); } }); return value;
  };
  const signals = (relRun === 'A' ? info : bInfo)?.signals.filter(s => s.identity && !s.ambiguity && s.unit) ?? [];
  const xId = signals.some(s => s.id === x) ? x : signals[0]?.id ?? '', yId = signals.some(s => s.id === y && s.id !== xId) ? y : signals.find(s => s.id !== xId)?.id ?? '';
  const selectedPair = comparison?.pairs.find(p => p.identity === identity);
  const min = plots ? Math.min(plots.a.min ?? 0, plots.b.min ?? 0) : 0, max = plots ? Math.max(plots.a.max ?? 0, plots.b.max ?? 0) : 1;
  return <section className="drive-analysis" aria-label="Comparative drive analysis">
    <span className="obd-kicker">06 / COMPARATIVE DRIVE ANALYSIS</span><h2>Find comparable moments.</h2><p>Run A: <strong>{name}</strong>. Phase labels describe measured operating regions. Both logs, mappings and results stay in this browser.</p>
    <details className="drive-rules"><summary>Phase rules, thresholds & limitations</summary><p>{PHASE_RULES}</p><p>Speed alone cannot prove engine idle, gear, road gradient or driver intent. RPM strengthens the idle label. Missing speed, ambiguous units and duplicate semantic columns remain unclassified. No vehicle fault is inferred.</p></details>
    {error && <p className="obd-error" role="alert">{error}</p>}
    {busy && <p className="obd-notice" role="status">Working locally… <button onClick={onCancel}>Cancel analysis and clear both runs</button></p>}
    <div className="drive-controls">{(['A', 'B'] as const).map(run => { const summary = summaries[run]; return summary && <div className={`drive-run run-${run}`} key={run}><h3>Run {run} regions</h3><label>Phase region {run}<select aria-label={`Phase region ${run}`} value={ids[run]} disabled={busy || !summary.total} onChange={e => { clearResults(); setRegions(old => ({ ...old, [run]: undefined })); setIds(old => ({ ...old, [run]: +e.target.value })); }}>{summary.segments.map(s => <option value={s.id} key={s.id}>{label(s)}</option>)}</select></label><p className="obd-footnote">{Object.entries(summary.durations).filter(([, duration]) => duration > 0).map(([phase, duration]) => `${phase}: ${n(duration)} s`).join(' · ')}</p>{summary.total > 200 && <div><button disabled={busy || summary.offset === 0} onClick={() => void act(() => phasePage(run, Math.max(0, summary.offset - 200)))}>Previous regions {run}</button><span>{summary.offset + 1}–{Math.min(summary.offset + 200, summary.total)} of {summary.total}</span><button disabled={busy || summary.offset + 200 >= summary.total} onClick={() => void act(() => phasePage(run, summary.offset + 200))}>Next regions {run}</button></div>}{regions[run] && <><RegionStats data={regions[run]} run={run} />{run === 'A' && <button onClick={() => onInspect(regions.A!.segment.start)}>Inspect this phase in Run A</button>}</>}</div>; })}</div>
    <details className="drive-advanced"><summary>A/B comparison</summary><p>Load and validate Run B, then select a phase region from each run. Context labels are organizational; they do not imply a repair outcome.</p><div className="drive-controls"><label>Comparison context<select value={context} onChange={e => setContext(e.target.value)}>{['Run 1 vs Run 2', 'Before repair vs After repair', 'Cold vs Warm', 'Baseline vs Modified'].map(v => <option key={v}>{v}</option>)}</select></label><label className="obd-button">{bInfo ? 'Replace Run B' : 'Load Run B'}<input aria-label="Choose Run B CSV log" disabled={busy} type="file" accept=".csv,.tsv,.txt" onChange={e => { const f = e.target.files?.[0]; if (f) void loadB(f, f.name); e.target.value = ''; }} /></label></div>
      <p className="drive-run-name">Run B: {bName || 'No log loaded'}</p>
      {preview && <div className="drive-b-preview"><h3>Run B · mapping and validation</h3><ImportPreview preview={preview} busy={busy} onReprocess={remapB} onBack={bInfo ? () => setPreview(null) : undefined} onAccept={() => void act(async () => { const r = await client.request({ kind: 'commit', run: 'B', revision: preview.revision }); if (mounted.current && 'kind' in r && r.kind === 'commit') { clearResults(); setBInfo(r.info); setPreview(null); await phasePage('B'); } })} /></div>}
      {bInfo && !preview && <><div className="drive-controls"><button disabled={busy} onClick={() => void remapB()}>Review Run B mapping</button><button disabled={busy} onClick={() => void act(async () => { await client.request({ kind: 'clear-b' }); clearResults(); setBInfo(null); setBName(''); setIds(old => ({ ...old, B: -1 })); setRegions(old => ({ A: old.A })); setSummaries(old => ({ A: old.A })); setRelRun('A'); })}>Remove Run B</button><button className="obd-primary" disabled={busy || ids.A < 0 || ids.B < 0} onClick={() => void act(async () => { const rev = generation.current; const r = await client.request({ kind: 'compare', a: ids.A, b: ids.B }); if (mounted.current && rev === generation.current && 'kind' in r && r.kind === 'compare') { setComparison(r.comparison); setIdentity(r.comparison.pairs[0]?.identity ?? ''); setPlots(null); } })}>Compare selected regions</button></div><details><summary>Run B quality & provenance</summary><p>{bInfo.format} · {bInfo.quality.parsed} records · {bInfo.quality.rejected} rejected · {bInfo.quality.missingTimes} missing timestamps · {bInfo.quality.duplicateTimes} duplicate · {bInfo.quality.backwardsTimes} backwards · {bInfo.quality.gaps} gaps</p>{bInfo.quality.warnings.map((w, i) => <p key={i}>{w}</p>)}{bInfo.signals.map(s => <p key={s.id}>{s.originalName} → {s.identity ?? 'custom'} · {s.originalUnit ?? '?'} → {s.unit ?? '?'} · {s.provenance?.reason}</p>)}</details></>}
      {comparison && !preview && <div className="drive-result" data-testid="comparison-result"><h3>{context}</h3><strong className="drive-match">{comparison.state}</strong><p>Run A {label(comparison.a.segment)}<br />Run B {label(comparison.b.segment)}</p><ul>{comparison.reasons.map(r => <li key={r}>{r}</li>)}</ul><h3>What changed?</h3><p>Absolute median differences in the displayed units. For percent signals, Δ is in percentage points.</p>{!comparison.changes.length && <p>No direct change observations: incompatible conditions or insufficient signal coverage.</p>}<div className="drive-stat-grid">{comparison.changes.map(c => <article key={c.identity} data-testid={`change-${c.identity}`}><strong>{c.identity}</strong><span>Median A {n(c.a)} → B {n(c.b)} {c.unit}</span><b>Δ B − A: {n(c.delta)} {c.unit}</b><small>A {c.countA} / B {c.countB} samples · coverage {pct(c.coverageA)} / {pct(c.coverageB)}</small><small>Selected regions above · {comparison.state}. Observed difference, no cause inferred.</small></article>)}</div>{['GOOD MATCH', 'PARTIAL MATCH'].includes(comparison.state) && <><div className="drive-controls"><label>Compatible signal<select aria-label="Comparison signal" disabled={busy} value={identity} onChange={e => { setIdentity(e.target.value); setPlots(null); }}>{comparison.pairs.map(p => <option key={p.identity} value={p.identity!}>{p.identity} · {p.unit}</option>)}</select></label><button disabled={busy || !identity} onClick={() => void act(async () => { const rev = generation.current; const r = await client.request({ kind: 'comparison-traces', a: ids.A, b: ids.B, identity }); if (mounted.current && rev === generation.current && 'kind' in r && r.kind === 'comparison-traces') setPlots(r.traces); })}>Show side-by-side traces</button></div><p>Each X axis starts at its selected region’s elapsed-time origin and retains real seconds and its own duration. Y scale is shared. No row alignment, time stretching or synchronized event claim.</p>{plots && <div className="drive-controls"><TracePlot data={plots.a} segment={comparison.a.segment} run="A" unit={selectedPair?.unit ?? ''} limits={[min, max]} /><TracePlot data={plots.b} segment={comparison.b.segment} run="B" unit={selectedPair?.unit ?? ''} limits={[min, max]} /></div>}</>}</div>}
    </details>
    <details className="drive-advanced"><summary>PID relationship explorer</summary><p>Uses the selected phase region of the chosen run. Each axis keeps its own physical unit; signals need not share a dimension.</p><div className="drive-controls"><label>Relationship run<select aria-label="Relationship run" value={relRun} disabled={busy} onChange={e => { setRelRun(e.target.value as Run); setX(''); setY(''); setRel(null); }}><option>A</option>{bInfo && <option>B</option>}</select></label><label>X signal<select aria-label="Relationship X" value={xId} disabled={busy} onChange={e => { setX(e.target.value); setRel(null); }}>{signals.map(s => <option value={s.id} key={s.id}>{s.identity} · {s.unit}</option>)}</select></label><label>Y signal<select aria-label="Relationship Y" value={yId} disabled={busy} onChange={e => { setY(e.target.value); setRel(null); }}>{signals.filter(s => s.id !== xId).map(s => <option value={s.id} key={s.id}>{s.identity} · {s.unit}</option>)}</select></label><label>Maximum pairing offset (s)<input aria-label="Pairing tolerance" type="number" min="0" max="2" step="0.05" value={tolerance} disabled={busy} onChange={e => { setTolerance(+e.target.value); setRel(null); }} /></label><button disabled={busy || !xId || !yId || ids[relRun] < 0} onClick={() => void act(async () => { const rev = generation.current; const r = await client.request({ kind: 'relationship', run: relRun, segment: ids[relRun], x: xId, y: yId, tolerance }); if (mounted.current && rev === generation.current && 'kind' in r && r.kind === 'relationship') setRel(r.relationship); })}>Explore relationship</button></div><details><summary>Timestamp pairing & Pearson method</summary><p>{PAIRING_POLICY}</p><p>Pearson r = Σ((x−mean x)(y−mean y)) / √(Σ(x−mean x)² × Σ(y−mean y)²), computed with online centered sums. Requires at least 3 pairs and nonzero variance on both axes. No statistical significance or diagnostic confidence is inferred.</p></details>{rel && <div data-testid="relationship-result"><h3>Run {relRun} · {regions[relRun] ? label(regions[relRun]!.segment) : 'selected region'}</h3><p><strong>Pearson r: {n(rel.pearson)}</strong> · {n(rel.count)} paired / {n(rel.eligible)} unique X samples · {n(rel.unmatched)} unmatched</p><p>Maximum |Δt| {n(rel.maxOffset)} s · mean |Δt| {n(rel.meanOffset)} s · {rel.futurePairs} Y samples after X · tolerance {rel.tolerance} s</p><p>{rel.note}{rel.pearson === null && ' Pearson unavailable: fewer than 3 pairs or a constant axis.'}</p><Scatter data={rel} xLabel={`${signals.find(s => s.id === rel.x)?.identity} (${signals.find(s => s.id === rel.x)?.unit})`} yLabel={`${signals.find(s => s.id === rel.y)?.identity} (${signals.find(s => s.id === rel.y)?.unit})`} /></div>}</details>
  </section>;
}
