"use client";
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-html-link-for-pages */

import { useState } from "react";
import { ArrowUpRight, Menu, X } from "lucide-react";

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main className="site-shell">
    <header className="site-header"><a className="brand" href="/" aria-label="TorqueGirl home"><span className="brand-mark">T</span><span>Torque<span>Girl</span><b>.com</b></span></a><nav className={menuOpen ? "nav-links is-open" : "nav-links"} aria-label="Main navigation"><a href="/" onClick={() => setMenuOpen(false)}>Home</a><a href="#explore" onClick={() => setMenuOpen(false)}>Machines</a><a href="#explore" onClick={() => setMenuOpen(false)}>Motorsport</a><a href="/engines" onClick={() => setMenuOpen(false)}>Engines</a><a href="/technology" onClick={() => setMenuOpen(false)}>Technology</a><a href="#how-it-works" onClick={() => setMenuOpen(false)}>Learn</a><a href="#about" onClick={() => setMenuOpen(false)}>About</a></nav><div className="header-actions"><button className="menu-button" aria-label={menuOpen ? "Close menu" : "Open menu"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line" />Power, decoded.</p><h1>Meet the machines that make power.</h1><p className="hero-intro">TorqueGirl explores the engineering behind racing cars, legendary engines, high-performance machines, and the technology that makes them extraordinary.</p><div className="hero-actions"><a className="button button-dark" href="#explore">Explore machines<ArrowUpRight size={17} /></a><a className="button button-outline" href="#how-it-works">How it works</a></div><p className="scroll-note"><span className="scroll-bar" />Scroll to explore</p></div><div className="hero-visual"><div className="hero-grid" /><div className="hero-label label-top">TG / 001 <span>●</span></div><div className="hero-label label-bottom">MACHINES / PERFORMANCE / ENGINEERING</div><div className="image-frame"><img src="/torque-girl-hero.png" alt="TorqueGirl standing beside a high-performance race car" fetchPriority="high" /></div></div></section>
    <section className="section explore-section" id="explore"><div className="section-heading"><div><p className="eyebrow"><span className="eyebrow-line" />The TorqueGirl index</p><h2>Start with the machine that sparks your curiosity.</h2></div><p>A growing library of engineering stories, organized around the systems that turn energy into motion.</p></div><div className="category-grid"><a className="category-card" href="#how-it-works"><span className="category-number">01</span><span className="category-title">Motorsport<ArrowUpRight size={18} /></span><span className="category-body">Race-bred decisions, from qualifying laps to endurance stints.</span></a><a className="category-card" href="#how-it-works"><span className="category-number">02</span><span className="category-title">Engines &amp; powertrains<ArrowUpRight size={18} /></span><span className="category-body">Where combustion, electricity, and torque become movement.</span></a><a className="category-card" href="#featured"><span className="category-number">03</span><span className="category-title">Extreme machines<ArrowUpRight size={18} /></span><span className="category-body">The boldest machines built to push a boundary.</span></a><a className="category-card" href="#how-it-works"><span className="category-number">04</span><span className="category-title">Engineering breakdown<ArrowUpRight size={18} /></span><span className="category-body">Clear explanations of the parts that make performance possible.</span></a><a className="category-card" href="#featured"><span className="category-number">05</span><span className="category-title">Iconic machines<ArrowUpRight size={18} /></span><span className="category-body">The designs that changed what machines could do.</span></a><a className="category-card" href="/technology"><span className="category-number">06</span><span className="category-title">Technology<ArrowUpRight size={18} /></span><span className="category-body">Materials, aerodynamics, cooling, and the trade-offs between them.</span></a></div></section>
    <section className="section scope-section" id="how-it-works"><div className="scope-intro"><p className="eyebrow light"><span className="eyebrow-line" />What we explore</p><h2>The difference is in the details.</h2><p>TorqueGirl is about more than speed. It is a field guide to the choices, compromises, and clever solutions inside extraordinary machines.</p></div><div className="scope-list"><div className="scope-item"><span>01</span><strong>Where power comes from</strong></div><div className="scope-item"><span>02</span><strong>How machines transfer power</strong></div><div className="scope-item"><span>03</span><strong>Why racing machines are engineered differently</strong></div><div className="scope-item"><span>04</span><strong>Materials, aerodynamics, and cooling</strong></div><div className="scope-item"><span>05</span><strong>Mechanical trade-offs</strong></div><div className="scope-item"><span>06</span><strong>Performance vs. efficiency</strong></div></div></section>
    <section className="section featured-section" id="featured"><div className="featured-art featured-article-art"><img src="/images/articles/torquegirl-nascar-v8-hero.png" alt="TorqueGirl beside a V8 racing engine in a stock car" loading="lazy" /></div><div className="featured-copy"><p className="eyebrow"><span className="eyebrow-line" />Featured machine</p><h2>How a NASCAR V8 engine works</h2><p>Follow the air, fuel, combustion, heat and engineering choices inside one of motorsport's most recognizable powertrains.</p><a className="text-link" href="/engines/how-a-nascar-v8-engine-works">Read the article <ArrowUpRight size={16} /></a></div></section>
    <section className="section featured-section" id="latest"><div className="featured-art featured-article-art"><img src="/images/articles/torquegirl-turbo-vs-supercharger-hero.png" alt="TorqueGirl comparing a turbocharger and supercharger on a workshop bench" loading="lazy" /></div><div className="featured-copy"><p className="eyebrow"><span className="eyebrow-line" />Latest from the garage</p><h2>Turbocharger vs supercharger</h2><p>Follow the energy: how exhaust flow or an engine-driven belt turns more air into performance.</p><a className="text-link" href="/engines/turbocharger-vs-supercharger">Read the article <ArrowUpRight size={16} /></a></div></section>
    <section className="section featured-section" id="engine-legends"><div className="featured-art featured-article-art"><img src="/images/articles/torquegirl-2jz-gte-hero.png" alt="TorqueGirl standing beside a Toyota 2JZ-GTE engine on a workshop stand" loading="lazy" /></div><div className="featured-copy"><p className="eyebrow"><span className="eyebrow-line" />Engine legends</p><h2>Why the 2JZ-GTE still matters</h2><p>Explore the engineering, durability, tuning headroom and Supra connection behind a thirty-year-old performance icon.</p><a className="text-link" href="/engines/toyota-2jz-gte-tuning-legend">Read the article <ArrowUpRight size={16} /></a></div></section>
    <section className="section featured-section" id="technology"><div className="featured-art featured-article-art"><img src="/images/articles/torquegirl-formula-downforce-hero.png" alt="TorqueGirl examining a Formula-style race car and its aerodynamic surfaces" loading="lazy" /></div><div className="featured-copy"><p className="eyebrow"><span className="eyebrow-line" />Technology</p><h2>How a Formula 1 car creates downforce</h2><p>Follow the airflow from the front wing to the floor and diffuser, and see how aerodynamic load becomes cornering performance.</p><a className="text-link" href="/technology/how-formula-1-car-creates-downforce">Read the article <ArrowUpRight size={16} /></a></div></section>
    <section className="about-section" id="about"><div className="about-image"><img src="/torque-girl-hero.png" alt="TorqueGirl in a race paddock" loading="lazy" /></div><div className="about-copy"><p className="eyebrow"><span className="eyebrow-line" />Meet TorqueGirl</p><h2>Your guide to the machinery behind the spectacle.</h2><p>TorqueGirl makes complex engineering easier to see, hear, and understand—without sanding away the wonder.</p></div></section>
    <section className="follow-section" id="follow"><div><p className="eyebrow light"><span className="eyebrow-line" />Follow the build</p><h2>New breakdowns, comparisons, and machine stories are on the way.</h2></div><a className="button button-light" href="mailto:hello@torquegirl.com">Stay in the loop<ArrowUpRight size={17} /></a></section>
    <footer className="site-footer"><div className="footer-top"><a className="brand brand-footer" href="/"><span className="brand-mark">T</span><span>Torque<span>Girl</span><b>.com</b></span></a><p>Machines. Performance. Real engineering.</p></div><div className="footer-bottom"><nav aria-label="Footer navigation"><a href="#about">About</a><a href="#explore">Categories</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="mailto:hello@torquegirl.com">Contact</a></nav><div className="footer-meta"><span>© {new Date().getFullYear()} TorqueGirl</span><span>English only</span></div></div></footer>
  </main>;
}
