"use client";

import { useState } from "react";
import { ArrowUpRight, Menu, X } from "lucide-react";

type Language = "en" | "id";
const content = {
  en: {
    nav: ["Explore", "How it works", "About"], eyebrow: "Power, decoded.", title: "Meet the machines that make power.", intro: "TorqueGirl explores the engineering behind racing cars, legendary engines, high-performance machines, and the technology that makes them extraordinary.", primary: "Explore machines", secondary: "How it works", scroll: "Scroll to explore", exploreEyebrow: "The TorqueGirl index", exploreTitle: "Start with the machine that sparks your curiosity.", exploreBody: "A growing library of engineering stories, organized around the systems that turn energy into motion.", categories: [["01", "Motorsport", "Race-bred decisions, from qualifying laps to endurance stints."], ["02", "Engines & powertrains", "Where combustion, electricity, and torque become movement."], ["03", "Extreme machines", "The boldest machines built to push a boundary."], ["04", "Engineering breakdown", "Clear explanations of the parts that make performance possible."], ["05", "Iconic machines", "The designs that changed what machines could do."], ["06", "Technology", "Materials, aerodynamics, cooling, and the trade-offs between them."]], scopeEyebrow: "What we explore", scopeTitle: "The difference is in the details.", scopeBody: "TorqueGirl is about more than speed. It is a field guide to the choices, compromises, and clever solutions inside extraordinary machines.", scopeItems: ["Where power comes from", "How machines transfer power", "Why racing machines are engineered differently", "Materials, aerodynamics, and cooling", "Mechanical trade-offs", "Performance vs. efficiency"], featuredLabel: "Featured machine", featuredTitle: "Coming soon", featuredBody: "The first deep-dive is being tuned. Check back for a machine worth taking apart, one system at a time.", aboutEyebrow: "Meet TorqueGirl", aboutTitle: "Your guide to the machinery behind the spectacle.", aboutBody: "TorqueGirl makes complex engineering easier to see, hear, and understand—without sanding away the wonder.", follow: "Follow the build", followBody: "New breakdowns, comparisons, and machine stories are on the way.", followCta: "Stay in the loop", footer: ["About", "Categories", "Privacy", "Terms", "Contact"]
  },
  id: {
    nav: ["Jelajahi", "Cara kerja", "Tentang"], eyebrow: "Tenaga, dibedah.", title: "Kenali mesin-mesin penghasil tenaga.", intro: "TorqueGirl membahas engineering di balik mobil balap, mesin legendaris, mesin berperforma tinggi, dan teknologi yang membuatnya luar biasa.", primary: "Jelajahi mesin", secondary: "Pelajari teknologinya", scroll: "Gulir untuk menjelajah", exploreEyebrow: "Indeks TorqueGirl", exploreTitle: "Mulai dari mesin yang membuatmu penasaran.", exploreBody: "Kumpulan cerita engineering yang terus bertumbuh, disusun berdasarkan sistem yang mengubah energi menjadi gerak.", categories: [["01", "Motorsport", "Keputusan yang lahir dari lintasan, dari kualifikasi hingga balap ketahanan."], ["02", "Mesin & powertrain", "Saat pembakaran, listrik, dan torsi menjadi gerak."], ["03", "Mesin ekstrem", "Mesin-mesin berani yang mendorong batas."], ["04", "Bedah engineering", "Penjelasan jernih tentang komponen yang menghasilkan performa."], ["05", "Mesin ikonik", "Desain yang mengubah kemungkinan sebuah mesin."], ["06", "Teknologi", "Material, aerodinamika, pendinginan, dan komprominya."]], scopeEyebrow: "Yang kami jelajahi", scopeTitle: "Perbedaannya ada pada detail.", scopeBody: "TorqueGirl bukan hanya soal kecepatan. Ini adalah panduan untuk memahami pilihan, kompromi, dan solusi cerdas di dalam mesin luar biasa.", scopeItems: ["Dari mana tenaga berasal", "Bagaimana mesin menyalurkan tenaga", "Mengapa mesin balap direkayasa berbeda", "Material, aerodinamika, dan pendinginan", "Kompromi mekanis", "Performa vs. efisiensi"], featuredLabel: "Mesin pilihan", featuredTitle: "Segera hadir", featuredBody: "Bedah mendalam pertama sedang dipersiapkan. Nantikan satu mesin yang akan kita bongkar, sistem demi sistem.", aboutEyebrow: "Kenalan dengan TorqueGirl", aboutTitle: "Pemandumu memahami mesin di balik pertunjukan.", aboutBody: "TorqueGirl membantu membuat engineering yang rumit lebih mudah dilihat, didengar, dan dipahami—tanpa menghilangkan rasa kagumnya.", follow: "Ikuti perjalanannya", followBody: "Bedah, perbandingan, dan cerita mesin baru sedang disiapkan.", followCta: "Tetap terhubung", footer: ["Tentang", "Kategori", "Privasi", "Ketentuan", "Kontak"]
  }
} as const;

export default function Home() {
  const [lang, setLang] = useState<Language>("en");
  const [menuOpen, setMenuOpen] = useState(false);
  const t = content[lang];
  return <main className="site-shell">
    <header className="site-header"><a className="brand" href="#top" aria-label="TorqueGirl home"><span className="brand-mark">T</span><span>Torque<span>Girl</span><b>.com</b></span></a><nav className={menuOpen ? "nav-links is-open" : "nav-links"} aria-label="Main navigation"><a href="#explore" onClick={() => setMenuOpen(false)}>{t.nav[0]}</a><a href="#how-it-works" onClick={() => setMenuOpen(false)}>{t.nav[1]}</a><a href="#about" onClick={() => setMenuOpen(false)}>{t.nav[2]}</a></nav><div className="header-actions"><div className="language-switcher" aria-label="Language selector"><button className={lang === "en" ? "active" : ""} onClick={() => setLang("en")}>EN</button><span>/</span><button className={lang === "id" ? "active" : ""} onClick={() => setLang("id")}>ID</button></div><button className="menu-button" aria-label={menuOpen ? "Close menu" : "Open menu"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div></header>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line" />{t.eyebrow}</p><h1>{t.title}</h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><a className="button button-dark" href="#explore">{t.primary}<ArrowUpRight size={17} /></a><a className="button button-outline" href="#how-it-works">{t.secondary}</a></div><p className="scroll-note"><span className="scroll-bar" />{t.scroll}</p></div><div className="hero-visual"><div className="hero-grid" /><div className="hero-label label-top">TG / 001 <span>●</span></div><div className="hero-label label-bottom">MACHINES / PERFORMANCE / ENGINEERING</div><div className="image-frame"><img src="/torque-girl-hero.png" alt="TorqueGirl standing beside a high-performance race car" fetchPriority="high" /></div></div></section>
    <section className="section explore-section" id="explore"><div className="section-heading"><div><p className="eyebrow"><span className="eyebrow-line" />{t.exploreEyebrow}</p><h2>{t.exploreTitle}</h2></div><p>{t.exploreBody}</p></div><div className="category-grid">{t.categories.map(([num, title, body]) => <a className="category-card" href="#featured" key={num}><span className="category-number">{num}</span><span className="category-title">{title}<ArrowUpRight size={18} /></span><span className="category-body">{body}</span></a>)}</div></section>
    <section className="section scope-section" id="how-it-works"><div className="scope-intro"><p className="eyebrow light"><span className="eyebrow-line" />{t.scopeEyebrow}</p><h2>{t.scopeTitle}</h2><p>{t.scopeBody}</p></div><div className="scope-list">{t.scopeItems.map((item, i) => <div className="scope-item" key={item}><span>0{i + 1}</span><strong>{item}</strong></div>)}</div></section>
    <section className="section featured-section" id="featured"><div className="featured-art"><div className="technical-ring" /><span className="featured-code">TG / FEATURED / 000</span><div className="featured-center">?</div></div><div className="featured-copy"><p className="eyebrow"><span className="eyebrow-line" />{t.featuredLabel}</p><h2>{t.featuredTitle}</h2><p>{t.featuredBody}</p><a className="text-link" href="#follow">{t.followCta} <ArrowUpRight size={16} /></a></div></section>
    <section className="about-section" id="about"><div className="about-image"><img src="/torque-girl-hero.png" alt="TorqueGirl in a race paddock" loading="lazy" /></div><div className="about-copy"><p className="eyebrow"><span className="eyebrow-line" />{t.aboutEyebrow}</p><h2>{t.aboutTitle}</h2><p>{t.aboutBody}</p></div></section>
    <section className="follow-section" id="follow"><div><p className="eyebrow light"><span className="eyebrow-line" />{t.follow}</p><h2>{t.followBody}</h2></div><a className="button button-light" href="mailto:hello@torquegirl.com">{t.followCta}<ArrowUpRight size={17} /></a></section>
    <footer className="site-footer"><div className="footer-top"><a className="brand brand-footer" href="#top"><span className="brand-mark">T</span><span>Torque<span>Girl</span><b>.com</b></span></a><p>Machines. Performance. Real engineering.</p></div><div className="footer-bottom"><nav aria-label="Footer navigation">{t.footer.map((item) => <a href={item === "Contact" || item === "Kontak" ? "mailto:hello@torquegirl.com" : "#top"} key={item}>{item}</a>)}</nav><div className="footer-meta"><span>© {new Date().getFullYear()} TorqueGirl</span><span>EN / ID</span></div></div></footer>
  </main>;
}
